@startuml

top to bottom direction

skinparam groupInheritance 2

' **********
' 类定义
' **********
struct AnalysisKey{
PASS ID
}

struct AnalysisSetKey {
PASS集合ID
}

together {

  class AllAnalysesOn {
    {static} +ID(): AnalysisKey
    {static} -SetKey
  }

  class CFGAnalyses {
    {static} + ID(): AnalysisKey
    {static} - SetKey
  }

}

together {

  class PreservedAnalyses {
    {static} +none(): PreservedAnalyses
    {static} +all(): PreservedAnalyses
    +preserve(): void
    +preserveSet(): void
    +abandon(): void
    +intersect(PreservedAnalyses &): void
  }

  class PreservedAnalysisChecker {
    - PreservedAnalyses PA
    - AnalysisKey ID
    - bool IsAbandoned
    + perserved(): bool
    + preservedWhenStateless(): bool
    {static} - AnalysisSetKey AllAnalysesKey
  }
}

together {
  Interface AnalysisManager {
    template<T> AnalysisManager

  }

  class TAnalysisManager_F<Functio> {
    AnalysisManager<Function>

  }

  class TAnalysisManager_M<Module> {
    AnalysisManager<Module>

  }

}

together {
  Interface PassManager {
    template <T> PassManger
  }

  class TPassManager_F<Functio> {
    PassManager<Function>
  }

  class TPassManager_M<Module> {
    PassManager<Module>
  }
}



struct PassInfoMixin {
  {static} +name(): void
  + printPipeline(): void
}

' **********
' 类关系
' **********
PreservedAnalyses                 #--               PreservedAnalysisChecker #line:lightGreen;text:lightGreen : frined


' AnalysisManager关系
AnalysisManager                   <|.down.                TAnalysisManager_F
AnalysisManager                   <|.down.                TAnalysisManager_M

' PassManager关系
PassManager                       <|.down.                TPassManager_F
PassManager                       <|.down.                TPassManager_M

@enduml