@startuml

title "Function IR类型分析"
top to bottom direction
skinparam groupInheritance 2

' **********
' 类定义
' **********

class Value {

}

class User {

}

class Instruction {

}

class Function {

}


' **********
' 类关系
' **********
Value                 <|--            User

User                  <|--            Instruction

ilist_node            <|--            Function
GlobalObject          <|--            Function

@enduml